spring:
    datasource:
#        type: com.alibaba.druid.pool.DruidDataSource
        hikari:
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.209.179:3306/quick_report?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
            username: fxtb
            password: fxtb2021!@#

#多数据源的配置
dynamic:
    datasource:
      slave1:
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.209.179:3306/czyj_base?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
            username: fxtb
            password: fxtb2021!@#
      slave2:
            driverClassName: com.mysql.cj.jdbc.Driver
            url: jdbc:mysql://192.168.209.179:3306/czyj_zbzs?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
            username: fxtb
            password: fxtb2021!@#
#短信地址
sms:
  url: http://192.168.209.178:9317/message/sendYdMess