# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    connectionTimeout: 180000
  port: 8090

  servlet:
    context-path: /
  shutdown: graceful

spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  freemarker:
    settings:
      output_format: HTMLOutputFormat
      recognize_standard_file_extensions: true
  rabbitmq:
    host: 192.168.1.253
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 15000
  mail:
    host: smtp.aliyun.com #smtp.qq.com
    port: 25
    username: feipcfeipc@aliyun.com #451019398@qq.com
    password: fei.8797548 #sxssfmyovywdbgfe

#    properties:
#      mail:
#        smtp:
#          socketFactory:
#            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xhtt.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
renren:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: 3e0b687834ae589067a24577fa48ca01[fxtb]
    # token有效时长，7天，单位秒
    expire: 60480000
    header: token
  file:
    path: d:/uploadPath/
  #path: /root/trainbdb/fxtb/files/
logging:
  config: classpath:logback-spring.xml
#  level:
#    com.xhtt: info # 改成你的mapper文件所在包路径
#  level.com.xhtt: info
  file:
    path: logs/
#  file: admin.log
#nblot:
#  ip: device.api.ct10649.com
#  port: 8743
#  appid: 4a5a3d76ffd84cb0a571fb8561bf5fb1
#  secret: 99ee7e8f3c1a4568b1fe7ed07f9509cb
#  callbackurl: http://cn-zj-bgp-2.sakurafrp.com:23963/app/nb/commandRsp
